apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payment

resources:
  - namespace.yaml
  # Gateway
  - gateway/deployment.yaml
  - gateway/service.yaml
  - gateway/hpa.yaml
  - gateway/pdb.yaml
  # Processor
  - processor/deployment.yaml
  - processor/service.yaml
  - processor/hpa.yaml
  - processor/pdb.yaml
  # Security
  - security/network-policies.yaml
  - security/rbac.yaml

labels:
  - pairs:
      managed-by: kustomize
    includeSelectors: false
